# Docker Compose configuration for Jina MCP Tools
version: '3.8'

services:
  jina-mcp-server:
    build: .
    container_name: jina-mcp-tools
    environment:
      - JINA_API_KEY=${JINA_API_KEY}
      - NODE_ENV=production
      - MCP_MODE=http
      - PORT=3000
    # For stdio transport, we need to handle it differently
    # You can either use this for HTTP transport or modify for stdio
    ports:
      - "3000:3000"
    restart: unless-stopped
    # If you want to use volumes for persistent data
    # volumes:
    #   - ./data:/app/data
    networks:
      - jina-network

networks:
  jina-network:
    driver: bridge
